#!/usr/bin/env python3
"""Extract exact StrongARM subcircuit from ngspice netlist generated by Xschem.

Usage: python3 extract_from_xschem_netlist.py <tb_netlist.spice> --out strongarm_11t.inc
Does NOT alter user's original Xschem schematic. Validates original pin order and MOS DGSB.
"""
import argparse
import re
from pathlib import Path
from run_mc import check_subckt

def extract(src:str)->str:
    m = re.search(r'(?ims)^\s*\.subckt\s+strongarm\b[^\n]*\n.*?^\s*\.ends(?:\s+strongarm)?\s*$',src)
    if not m:
        raise ValueError('StrongARM .subckt ... .ends not found; export hierarchical SPICE netlist first')
    sub=m.group(0).strip()+"\n"
    check_subckt(sub)
    return sub

if __name__=='__main__':
    ap=argparse.ArgumentParser()
    ap.add_argument('netlist',type=Path)
    ap.add_argument('--out',type=Path,default=Path('strongarm_11t.inc'))
    a=ap.parse_args()
    content=extract(a.netlist.read_text())
    a.out.write_text(content)
    print('Validated and wrote',a.out)
